### ISSUE TITLE
Cant register new account

### ISSUE THREAD

**Issue by oxplay2** [jMonkeyEngine/SoftwareStore#6]
HUB post:

https://hub.jmonkeyengine.org/t/cannot-login-to-jme-store/43857/4

Im not sure if it will be rebuilded anyway, but in any case would need to fix.

**Comment by riccardobl** [comment]
This was caused by unhandled exceptions in case of failure when requesting the avatars generated by this service https://eu.ui-avatars.com/
I applies a quick workaround in: https://github.com/jMonkeyEngine/SoftwareStore/commit/7f5cbff707e6ea563efbe25718c82b5173dbb9ab
And opened a new issue, to remove or fix the call,  here: https://github.com/jMonkeyEngine/SoftwareStore/issues/8
